variable "s3_bucket_name" {
  description = "Bucket name to store the state generated by terraform templates"
  type = string
}

variable "dynamodb_table_name" {
 description = "DynamoDB table to store terraform state lock" 
  type = string
}