version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    commands:
      - "echo ## Installing DOCKER"
      - "sudo yum install -y yum-utils"
      #- "sudo amazon-linux-extras install docker"
      - "sudo yum install -y docker"
      #- "sudo systemctl start docker.service"
      #- "sudo usermod -a -G docker ec2-user"
  build:
    commands:
      - "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 678955123808.dkr.ecr.us-east-1.amazonaws.com"
      - "sudo docker build -t backend-terraform-cicd-java-eks-dev-ecr-repository ."
      - "sudo docker tag backend-terraform-cicd-java-eks-dev-ecr-repository:latest 678955123808.dkr.ecr.us-east-1.amazonaws.com/backend-terraform-cicd-java-eks-dev-ecr-repository:latest"
      - "sudo docker push 678955123808.dkr.ecr.us-east-1.amazonaws.com/backend-terraform-cicd-java-eks-dev-ecr-repository:latest"
artifacts:
  files:  
    - '**/*'
