version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    commands:
      - "echo ## Installing JAVA 11"
      - "sudo yum install -y yum-utils"
      - "sudo yum install java-11-amazon-corretto-headless -y"
      - "java -version"
      - "echo ## Installing MAVEN LATEST VERSION"
      - "wget https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz"
      - "tar xzvf apache-maven-3.9.8-bin.tar.gz"
      - "export PATH=$(pwd)/apache-maven-3.9.8/bin:$PATH"
      - "mvn -v"
  build:
    commands:
      - "mvn dependency:resolve-plugins"
      - "mvn clean install"
      - "mvn compile -X"
artifacts:
  files:  
    - '**/*'
