name: API_Gateway_Prod
run-name: ${{ github.actor }} is running pipeline for API GATEWAY settings 🚀
on: 
  push:
    paths:
      - 'us-east-1/env/prod/clients/financial-client-a/**'
      - '.github/workflows/**'