name: API_Gateway_Prod
run-name: ${{ github.actor }} is running pipeline for API GATEWAY settings 🚀
on: 
  push:
    paths:
      - 'us-east-1/env/prod/gateway-api-eks/**'
      - '.github/workflows/**'

jobs:
  gateway_plan:
    needs: network_apply
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.plan.yml@main
    with:
      component_path: 'us-east-1/env/prod/gateway-api-eks'
      environment: Production
      component: gateway-api-eks
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  gateway_apply:
    needs: gateway_plan
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.apply.yml@main
    with:
      component_path: 'us-east-1/env/prod/gateway-api-eks'
      environment: Production
      component: gateway-api-eks
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  # network_destroy:
  #   needs: network_apply
  #   uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/network.workflow.destroy.yml@main
  #   with:
  #     component_path: 'us-east-1/env/prod/network'
  #     environment: Production
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}