name: API_Gateway_Prod
run-name: ${{ github.actor }} is running pipeline for API GATEWAY settings 🚀
on: 
  push:
    paths:
      - 'us-east-1/env/prod/gateway-api-eks/**'
      - '.github/workflows/**'

jobs:
  wait_for:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ github.token }}
          repo: ayrtonfidel9
          owner: aws-technical-test-tf
          workflow: network.prod.us-east-1.yml
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ github.token }}
          repo: return-dispatch
          owner: codex-
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000
  gateway_plan:
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.plan.yml@main
    with:
      component_path: 'us-east-1/env/prod/gateway-api-eks'
      environment: Production
      component: gateway-api-eks
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  gateway_apply:
    needs: gateway_plan
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.apply.yml@main
    with:
      component_path: 'us-east-1/env/prod/gateway-api-eks'
      environment: Production
      component: gateway-api-eks
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  # network_destroy:
  #   needs: network_apply
  #   uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.destroy.yml@main
  #   with:
  #     component_path: 'us-east-1/env/prod/gateway-api-eks'
  #     environment: Production
  #     component: gateway-api-eks
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}