name: Network_Prod
run-name: ${{ github.actor }} is running pipeline for Network settings 🚀
on: 
  push:
    paths:
      - 'us-east-1/env/prod/network/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  network_plan:
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.plan.yml@main
    with:
      component_path: 'us-east-1/env/prod/network'
      environment: Production
      component: network
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  network_apply:
    needs: network_plan
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.apply.yml@main
    with:
      component_path: 'us-east-1/env/prod/network'
      environment: Production
      component: network
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  # network_destroy:
  #   needs: network_apply
  #   uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/workflow.destroy.yml@main
  #   with:
  #     component_path: 'us-east-1/env/prod/network'
  #     environment: Production
  #     component: network
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    