name: validate-plan-deploy
on:
  workflow_call:
    inputs:
      component_path:
        description: "Path of terraform component"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.11
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ayrton
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - name: Validate Network settings
        working-directory: ${{ inputs.component_path }}
        run: sh network-validate.sh
  