name: validate-plan-deploy
on:
  workflow_call:
    inputs:
      component_path:
        description: "Path of terraform component"
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.11
    steps:
      - name: Validate Network settings
        working-directory: ${{ github.workspace }}/${{ inputs.component_path }}
        run: sh ./network-validate.sh
  