name: Network
run-name: ${{ github.actor }} is Validating Terraform project 🚀
on: 
  push:
    paths:
      - 'us-east-1/env/prod/network/**'
      - '.github/workflows/**'

jobs:
  network-stages:
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/terraform-workflow.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      component_path: 'us-east-1/env/prod/network/'
