name: Network
run-name: ${{ github.actor }} is Validating Terraform project 🚀
on: 
  push:
    paths:
      - 'us-east-1/env/prod/network/**'
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.11
    steps: 
      - name: Validate Network settings
        working-directory: ${{ inputs.component_path }}
        run: bash network-validate.sh
